### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by DillonAd** [DillonAd/Evolution#10]
It would be nice to have a logo for when this gets published as a `dotnet` global tool. Humor is highly encouraged!

**Comment by jessica3oreno** [comment]
I would like to try

**Comment by richardbmx** [comment]
@DillonAd  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by richardbmx** [comment]
@DillonAd  I would like to present this logo proposal designed using the word EVO to give identity to your project with a modern and minimalist style, at the same time it is simple and very easy to remember, as you can see it fits very well in different backgrounds and colors.

![logo 114](https://user-images.githubusercontent.com/35604837/47056488-8dd46880-d18a-11e8-839a-426e357a6241.png)

**Comment by DillonAd** [comment]
@richardbmx Wow! Those look amazing! Please put in a PR!

**Comment by richardbmx** [comment]
@DillonAd  Sorry not to do the PR I can generate a google folder for you with all the necessary files to use the logo

**Comment by richardbmx** [comment]
@DillonAd  Here I give you the link with all the necessary files to use the logo, inside you find different variations of the logo to be used in different applications as well as the original files to edit them if you need it. Any questions you can write me I am ready for next projects if you wish...

[Google Drive](https://drive.google.com/open?id=1I4GKMgCzcpMLrIp9YiisiZnu-WIUwIXB)

**Comment by richardbmx** [comment]
@DillonAd  I have learned to perform the pull reques with your project I have made one with the incorporation of the logotype ;-)
