### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by DillonAd** [DillonAd/Evolution#2]
At the moment code coverage is at  11.5% according to SonarCloud. There really needs to be more unit tests. 

Another way to increase code coverage is to find a way to exclude the integration test directory from the SonarCloud metrics since the PL/SQL files are being included.

**Comment by drSte** [comment]
may I help with this?

**Comment by DillonAd** [comment]
That would be awesome!

Edit: If you have any trouble with the integration tests, let me know! I'd love to hear about any pain points so I can update the documentation and not make it a pain for people to contribute.

**Comment by dpisanu** [comment]
do you have your sonar config at hand for the repo? you can exclude files in there so they won't be taken into account.

**Comment by DillonAd** [comment]
I had seen something about excluding files but haven’t dug into it yet. I did notice that the PL/SQL test files are getting included so that’s probably not helping.

**Comment by DillonAd** [comment]
This description is far too vague to be useful. I apologize for giving such a crappy requirement.
